import type { Event, User, Organizer, PlayerProfile, LiveMatch, CorporatePackage, Ticket } from './types'

export const mockOrganizers: Organizer[] = [
  { id: 'o1', name: 'Mumbai Sports Club', bio: 'Premier sports org since 2015. 200+ events, 50K+ players.', events_hosted: 89, rating: 4.8, total_reviews: 312, verification_status: 'verified' },
  { id: 'o2', name: 'BKC Football Academy', bio: 'Professional football training and tournaments.', events_hosted: 45, rating: 4.7, total_reviews: 187, verification_status: 'verified' },
  { id: 'o3', name: 'Powai Sports Arena', bio: 'Multi-sport facility hosting weekly tournaments.', events_hosted: 63, rating: 4.6, total_reviews: 241, verification_status: 'verified' },
  { id: 'o4', name: 'GameOn Esports', bio: 'India\'s fastest growing esports tournament platform.', events_hosted: 120, rating: 4.9, total_reviews: 580, verification_status: 'verified' },
  { id: 'o5', name: 'Fit India Corp', bio: 'Corporate wellness and sports event specialists.', events_hosted: 34, rating: 4.5, total_reviews: 98, verification_status: 'verified' },
]

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'Mumbai Premier Cricket League Season 4',
    description: 'The biggest cricket tournament in Mumbai! T20 format across 5 grounds. DRS enabled. 160 teams, 1,280 players. Umpired matches with video review for finals.',
    category: 'cricket', event_type: 'tournament', status: 'filling',
    banner_color: '#7F1D1D', emoji: '🏏',
    date: '2025-06-14', time: '09:00 AM', registration_deadline: '2025-06-10',
    location: { venue_name: 'Wankhede Stadium', address: 'D Rd, Churchgate', city: 'Mumbai', state: 'Maharashtra', landmark: 'Near Marine Lines station' },
    max_participants: 160, current_participants: 128,
    team_config: { min_players: 8, max_players: 12, max_teams: 16 },
    payment_type: 'prize_pool', entry_fee: 5000, prize_pool: 250000,
    prizes: [
      { position: 1, label: 'Winner', amount: 150000, description: 'Trophy + Medal + Certificate' },
      { position: 2, label: 'Runner Up', amount: 75000, description: 'Medal + Certificate' },
      { position: 3, label: '3rd Place', amount: 25000, description: 'Medal + Certificate' },
    ],
    escrow_protected: true, skill_level: 'intermediate',
    rules: [
      { title: 'Format', description: 'T20 format. Group stage followed by knockouts. Finals are 25 overs.' },
      { title: 'Team Composition', description: 'Min 8, max 12 players. Playing XI must be declared 30 mins before.' },
      { title: 'Equipment', description: 'White kit mandatory for knockouts. Helmets provided for batters.' },
      { title: 'Fair Play', description: 'GPS check-in 20 mins before match. No-show = disqualification.' },
    ],
    organizer: mockOrganizers[0], created_at: '2025-05-01',
    equipment_provided: true, refund_policy: 'Full refund if cancelled by organiser. 50% refund up to 7 days before event.',
  },
  {
    id: '2',
    title: 'BKC 5-a-side Football League',
    description: 'Weekly 5-a-side league on premium synthetic turf. FIFA-standard rules. League format over 8 weeks with playoff finals. Perfect for office teams.',
    category: 'football', event_type: 'league', status: 'upcoming',
    banner_color: '#14532D', emoji: '⚽',
    date: '2025-06-15', time: '06:00 PM', registration_deadline: '2025-06-12',
    location: { venue_name: 'BKC Sports Ground', address: 'Bandra Kurla Complex', city: 'Mumbai', state: 'Maharashtra', landmark: 'Near MMRDA Ground' },
    max_participants: 64, current_participants: 48,
    team_config: { min_players: 5, max_players: 7, max_teams: 8 },
    payment_type: 'prize_pool', entry_fee: 800, prize_pool: 80000,
    prizes: [
      { position: 1, label: 'Champions', amount: 50000 },
      { position: 2, label: 'Runners Up', amount: 20000 },
      { position: 3, label: 'Third Place', amount: 10000 },
    ],
    escrow_protected: true, skill_level: 'all',
    rules: [
      { title: 'Format', description: '5-a-side. 20 min halves. Golden goal in knockout extra time.' },
      { title: 'Footwear', description: 'Astro turf shoes or flats only. No studs allowed.' },
    ],
    organizer: mockOrganizers[1], created_at: '2025-05-10',
    equipment_provided: false, refund_policy: 'Full refund if cancelled. No refund after registration closes.',
  },
  {
    id: '3',
    title: 'Powai Kabaddi Open Championship',
    description: 'Traditional kabaddi tournament open to all skill levels. Standard Pro Kabaddi rules. Great for beginners and pros alike.',
    category: 'kabaddi', event_type: 'tournament', status: 'upcoming',
    banner_color: '#4A1D96', emoji: '🤼',
    date: '2025-06-18', time: '09:30 AM', registration_deadline: '2025-06-15',
    location: { venue_name: 'Powai Sports Club', address: 'Hiranandani Gardens', city: 'Mumbai', state: 'Maharashtra' },
    max_participants: 32, current_participants: 22,
    team_config: { min_players: 7, max_players: 12, max_teams: 4 },
    payment_type: 'paid', entry_fee: 800, prize_pool: 0,
    prizes: [], escrow_protected: true, skill_level: 'all',
    rules: [{ title: 'Format', description: 'Pro Kabaddi League rules. 20 min halves.' }],
    organizer: mockOrganizers[2], created_at: '2025-05-15',
    equipment_provided: false, refund_policy: 'No refund after registration.',
  },
  {
    id: '4',
    title: 'All India Badminton Open 2025',
    description: 'Open badminton championship for singles and doubles. BWF rules. Multiple categories: Men\'s Singles, Women\'s Singles, Mixed Doubles.',
    category: 'badminton', event_type: 'tournament', status: 'upcoming',
    banner_color: '#1E3A5F', emoji: '🏸',
    date: '2025-06-21', time: '10:00 AM', registration_deadline: '2025-06-17',
    location: { venue_name: 'Navy Nagar Sports Complex', address: 'Colaba', city: 'Mumbai', state: 'Maharashtra' },
    max_participants: 128, current_participants: 96,
    payment_type: 'prize_pool', entry_fee: 1200, prize_pool: 50000,
    prizes: [
      { position: 1, label: 'Champion', amount: 30000 },
      { position: 2, label: 'Runner Up', amount: 15000 },
      { position: 3, label: 'Semi-Final', amount: 2500 },
    ],
    escrow_protected: true, skill_level: 'intermediate',
    rules: [{ title: 'Format', description: 'BWF rules. Best of 3 sets. Finals best of 5.' }],
    organizer: mockOrganizers[0], created_at: '2025-05-20',
    equipment_provided: false, refund_policy: '50% refund up to 5 days before.',
  },
  {
    id: '5',
    title: 'Friday Night Basketball Pickup',
    description: 'Casual 3-on-3 and 5-on-5 pickup basketball every Friday. No teams needed, just show up and play.',
    category: 'basketball', event_type: 'casual', status: 'upcoming',
    banner_color: '#7C2D12', emoji: '🏀',
    date: '2025-06-20', time: '07:00 PM', registration_deadline: '2025-06-20',
    location: { venue_name: 'Juhu Beach Basketball Court', address: 'Juhu Tara Road', city: 'Mumbai', state: 'Maharashtra' },
    max_participants: 30, current_participants: 18,
    payment_type: 'free', entry_fee: 0, prize_pool: 0,
    prizes: [], escrow_protected: false, skill_level: 'all',
    rules: [{ title: 'Format', description: 'Casual pickup. First to 11 points wins. Winner stays.' }],
    organizer: mockOrganizers[2], created_at: '2025-06-01',
    equipment_provided: true, refund_policy: 'Free event, no payment needed.',
  },
  {
    id: '6',
    title: 'BGMI Pro League Season 2',
    description: 'Competitive BGMI squad tournament. 50 squads, 200 players. Live streamed. Custom rooms with anti-cheat enabled.',
    category: 'esports', event_type: 'tournament', status: 'live',
    banner_color: '#1A1A2E', emoji: '🎮',
    date: '2025-06-06', time: '02:00 PM', registration_deadline: '2025-06-05',
    location: { venue_name: 'Online', address: 'BGMI Custom Room', city: 'Online', state: 'India' },
    max_participants: 200, current_participants: 200,
    team_config: { min_players: 4, max_players: 4, max_teams: 50 },
    payment_type: 'prize_pool', entry_fee: 500, prize_pool: 100000,
    prizes: [
      { position: 1, label: 'Winner', amount: 60000 },
      { position: 2, label: '2nd Place', amount: 25000 },
      { position: 3, label: '3rd Place', amount: 10000 },
      { position: 4, label: 'MVP', amount: 5000 },
    ],
    escrow_protected: true, skill_level: 'advanced',
    rules: [
      { title: 'Anti-Cheat', description: 'Screen share mandatory. Any cheat = instant disqualification.' },
      { title: 'Format', description: '6 matches. Points-based system. Top 3 teams win prizes.' },
    ],
    organizer: mockOrganizers[3], created_at: '2025-05-15',
    equipment_provided: false, refund_policy: 'No refund — esports event.',
  },
  {
    id: '7',
    title: 'Sunday Morning Volleyball',
    description: 'Beach volleyball every Sunday. Casual 6v6 on sand. Beginners welcome!',
    category: 'volleyball', event_type: 'casual', status: 'upcoming',
    banner_color: '#065F46', emoji: '🏐',
    date: '2025-06-22', time: '07:00 AM', registration_deadline: '2025-06-21',
    location: { venue_name: 'Juhu Beach', address: 'Juhu', city: 'Mumbai', state: 'Maharashtra' },
    max_participants: 24, current_participants: 10,
    payment_type: 'free', entry_fee: 0, prize_pool: 0,
    prizes: [], escrow_protected: false, skill_level: 'beginner',
    rules: [{ title: 'Format', description: 'Casual 6v6. FIVB rules. No spikes for beginners group.' }],
    organizer: mockOrganizers[2], created_at: '2025-06-01',
    equipment_provided: true, refund_policy: 'Free event.',
  },
  {
    id: '8',
    title: 'Corporate Table Tennis Championship',
    description: 'Inter-company table tennis tournament. Singles and doubles. ITTF rules. Great networking opportunity.',
    category: 'table_tennis', event_type: 'tournament', status: 'upcoming',
    banner_color: '#1E3A8A', emoji: '🏓',
    date: '2025-06-28', time: '11:00 AM', registration_deadline: '2025-06-24',
    location: { venue_name: 'Bandra-Kurla TT Club', address: 'BKC', city: 'Mumbai', state: 'Maharashtra' },
    max_participants: 64, current_participants: 34,
    payment_type: 'paid', entry_fee: 600, prize_pool: 0,
    prizes: [], escrow_protected: true, skill_level: 'all',
    rules: [{ title: 'Format', description: 'ITTF rules. 11-point games, best of 5.' }],
    organizer: mockOrganizers[4], created_at: '2025-06-02',
    equipment_provided: true, refund_policy: 'Full refund up to 3 days before.',
  },
]

export const mockUser: User = {
  id: 'u1',
  name: 'Arjun Rao',
  username: 'arjun_plays',
  email: 'arjun@kologic.ai',
  phone: '+91 98765 43210',
  city: 'Mumbai',
  bio: 'Cricket enthusiast & weekend warrior. 3x tournament winner. Love kabaddi too!',
  sports_interests: ['cricket', 'kabaddi', 'badminton'],
  wallet_balance: 2500,
  events_participated: 18,
  events_won: 3,
  total_winnings: 42000,
  verification_status: 'verified',
}

export const mockTickets: Ticket[] = [
  {
    id: 't1', event: mockEvents[0], ticket_number: 'TGO-2406-001',
    registered_at: '2025-05-20', status: 'upcoming',
    amount_paid: 5000, participant_name: 'Arjun Rao', team_name: 'Powai Strikers',
  },
  {
    id: 't2', event: mockEvents[1], ticket_number: 'TGO-2406-002',
    registered_at: '2025-05-25', status: 'upcoming',
    amount_paid: 800, participant_name: 'Arjun Rao', team_name: 'FC Hiranandani',
  },
  {
    id: 't3', event: mockEvents[2], ticket_number: 'TGO-2406-003',
    registered_at: '2025-05-28', status: 'upcoming',
    amount_paid: 800, participant_name: 'Arjun Rao', team_name: 'Powai Raiders',
  },
  {
    id: 't4', event: { ...mockEvents[4], status: 'completed', date: '2025-05-17' }, ticket_number: 'TGO-2405-044',
    registered_at: '2025-05-10', status: 'completed',
    amount_paid: 0, participant_name: 'Arjun Rao',
  },
]

export const mockPlayerProfile: PlayerProfile = {
  user: mockUser,
  level: 12,
  xp: 3400,
  xp_to_next: 5000,
  win_rate: 68,
  current_streak: 4,
  best_streak: 7,
  recent_form: ['W', 'W', 'L', 'W', 'W'],
  available_days: ['Saturday', 'Sunday', 'Friday evening'],
  looking_for: 'Cricket team for weekend tournaments. Also open to kabaddi.',
  sport_stats: [
    { category: 'cricket', matches: 24, wins: 16, losses: 6, draws: 2, highlights: { 'Avg Score': '42', 'Best': '98*', 'Wickets': '14', 'Economy': '6.2' } },
    { category: 'kabaddi', matches: 12, wins: 9, losses: 3, draws: 0, highlights: { 'Raid Points': '87', 'Tackle Points': '34', 'Avg Raid': '7.2' } },
    { category: 'badminton', matches: 8, wins: 5, losses: 3, draws: 0, highlights: { 'Win Rate': '62%', 'Sets Won': '18' } },
  ],
  achievements: [
    { id: 'a1', emoji: '🏆', title: 'Tournament Winner', description: 'Won your first tournament', unlocked: true, unlocked_at: '2024-08-15' },
    { id: 'a2', emoji: '🔥', title: 'Hot Streak', description: '5 wins in a row', unlocked: true, unlocked_at: '2025-01-22' },
    { id: 'a3', emoji: '⭐', title: 'Rising Star', description: 'Reach Level 10', unlocked: true, unlocked_at: '2025-03-10' },
    { id: 'a4', emoji: '💎', title: 'Diamond Player', description: 'Reach Level 20', unlocked: false },
    { id: 'a5', emoji: '👑', title: 'Champion', description: 'Win 5 tournaments', unlocked: false },
    { id: 'a6', emoji: '🌍', title: 'Globetrotter', description: 'Play in 5 different cities', unlocked: false },
  ],
}

export const mockLiveMatches: LiveMatch[] = [
  {
    id: 'l1', event_id: '6',
    title: 'BGMI Pro League — Match 3',
    category: 'esports', emoji: '🎮', color: '#1A1A2E',
    team_a: 'Team Alpha', team_b: 'Neon Blaze',
    score_a: '1st', score_b: '2nd',
    status: 'In Progress — Zone 3',
    prize_pool: 100000, viewers: 2847,
    updates: [
      { time: '18:42', text: 'Team Alpha eliminates Hydra Squad — 15 kills total', type: 'info' },
      { time: '18:39', text: 'Neon Blaze wins Chicken Dinner in Match 2!', type: 'point' },
      { time: '18:31', text: 'Zone closes to Georgopol — 12 teams remaining', type: 'info' },
    ],
  },
  {
    id: 'l2', event_id: '1',
    title: 'MPCL — QF: Powai Strikers vs Marine Lines XI',
    category: 'cricket', emoji: '🏏', color: '#7F1D1D',
    team_a: 'Powai Strikers', team_b: 'Marine Lines XI',
    score_a: '142/4 (16.0)', score_b: '98/6 (14.2)',
    status: 'Marine Lines Batting — Over 14.2',
    prize_pool: 250000, viewers: 1203,
    updates: [
      { time: '18:55', text: 'WICKET! Sharma caught at slip for 34', type: 'wicket' },
      { time: '18:48', text: 'SIX! Mehta launches one over long-on', type: 'point' },
      { time: '18:40', text: 'FOUR! Edge races through gully', type: 'point' },
    ],
  },
  {
    id: 'l3', event_id: '2',
    title: 'BKC League — Week 3: FC Hiranandani vs BKC United',
    category: 'football', emoji: '⚽', color: '#14532D',
    team_a: 'FC Hiranandani', team_b: 'BKC United',
    score_a: '2', score_b: '1',
    status: '2nd Half — 67\'',
    prize_pool: 80000, viewers: 432,
    updates: [
      { time: '67\'', text: 'GOAL! Rajan doubles the lead for FC Hiranandani', type: 'goal' },
      { time: '54\'', text: 'GOAL! Patel equalizes for BKC United', type: 'goal' },
      { time: '23\'', text: 'GOAL! Sharma opens the scoring', type: 'goal' },
    ],
  },
]

export const mockCorporatePackages: CorporatePackage[] = [
  {
    id: 'cp1', name: 'Team Day', price: 15000,
    participants: '20–40 employees', duration: '1 Day',
    sports: ['Cricket', 'Football', 'Badminton', 'Table Tennis'],
    includes: ['Venue booking', 'Equipment', 'Referee/Umpire', 'Snacks & Water', 'Certificate of participation', 'Event photos'],
    popular: false,
  },
  {
    id: 'cp2', name: 'Corporate Olympics', price: 45000,
    participants: '50–100 employees', duration: '2 Days',
    sports: ['Cricket', 'Football', 'Basketball', 'Badminton', 'Volleyball', 'Table Tennis', 'Tug of War', 'Relay Race'],
    includes: ['Full venue', 'All equipment', 'Professional referees', 'Lunch & refreshments', 'Trophies & medals', 'Full event photography', 'Live scoring app', 'MC & announcer'],
    popular: true,
  },
  {
    id: 'cp3', name: 'League Season', price: 120000,
    participants: '100–200 employees', duration: '8 Weeks',
    sports: ['Cricket', 'Football', 'Badminton', 'Basketball', 'Table Tennis'],
    includes: ['Weekly fixtures', 'Dedicated venue slots', 'League management app', 'Live leaderboard', 'All equipment', 'Referees & scoring', 'Mid-season party', 'Grand finale event', 'Year-round stats dashboard', 'Winner certificates & trophies'],
    popular: false,
  },
]

export const mockPlayers = [
  { id: 'p1', name: 'Rahul Sharma', city: 'Mumbai', sport: 'cricket' as const, skill: 'advanced', rating: 4.8, events: 34, available: 'Weekends', looking_for: 'Competitive cricket team, T20 format.', verified: true },
  { id: 'p2', name: 'Priya Nair', city: 'Mumbai', sport: 'badminton' as const, skill: 'intermediate', rating: 4.6, events: 21, available: 'Evenings', looking_for: 'Mixed doubles partner for tournaments.', verified: true },
  { id: 'p3', name: 'Karan Mehta', city: 'Mumbai', sport: 'football' as const, skill: 'intermediate', rating: 4.4, events: 18, available: 'Weekends', looking_for: '5-a-side team. Can play any position.', verified: false },
  { id: 'p4', name: 'Anjali Singh', city: 'Pune', sport: 'kabaddi' as const, skill: 'pro', rating: 4.9, events: 52, available: 'All days', looking_for: 'State-level kabaddi team or tournaments.', verified: true },
  { id: 'p5', name: 'Dev Patel', city: 'Mumbai', sport: 'basketball' as const, skill: 'beginner', rating: 4.2, events: 8, available: 'Weekends', looking_for: 'Casual basketball, just for fun!', verified: false },
  { id: 'p6', name: 'Sneha Rao', city: 'Mumbai', sport: 'volleyball' as const, skill: 'intermediate', rating: 4.5, events: 14, available: 'Sundays', looking_for: 'Beach volleyball team.', verified: true },
]
